/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajaservicios;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import paneles.*;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperReport;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import net.proteanit.sql.DbUtils;
import principal.GenerarNumero;
import static principal.PrincipalAdministrador.escritorio;
import lista_productos_servicios.Producto;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import lista_productos_servicios.ProductoDAO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import clases_cajas_servicios.laboratorio;
/**
 *
 * @author Rojeru San
 */
public class caja_laboratorio extends javax.swing.JInternalFrame {
SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
Connection con=null;
Date dato = null;
ResultSet rs=null;
PreparedStatement pst=null;
static Conexion cc = new Conexion();
 static Connection cn = cc.ConnectDB();
     ProductoDAO pdao = new ProductoDAO();
     DefaultTableModel modelo = new DefaultTableModel();
    String idp;
    int cant;
    double pre;
    double tpagar;
    /**
     * Creates new form NewJInternalFrame
     */
     public boolean estacerrado(Object obj) {
        JInternalFrame[] activos = escritorio.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }
 int filas;
    DefaultTableModel m;
    public caja_laboratorio() {
        initComponents();
        tablaCaja.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tablaCaja.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        tableCaja.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tableCaja.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        this.setFrameIcon(new ImageIcon(getClass().getResource("/imagenes/caja/icono.png")));
        tablaCaja.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con= Conexion.ConnectDB();
        limpiaCampos();
        thishide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        selectestado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        thishide = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlChange = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        c_search_tbl = new app.bolivia.swing.JCTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        buscF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCaja = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnsalestoday = new rsbuttom.RSButtonMetro();
        btnallsales = new rsbuttom.RSButtonMetro();
        btnrecievable = new rsbuttom.RSButtonMetro();
        txttotalcaja = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numFac = new javax.swing.JLabel();
        rbcontado = new javax.swing.JRadioButton();
        rbcredito = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        txtImporte = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCambio = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCalcular = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        txtpaciente = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        btnVender1 = new principal.MaterialButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        btnservicios = new principal.MaterialButton();
        btnservicios1 = new principal.MaterialButton();
        isv = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCaja = new javax.swing.JTable();
        txttotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCancelar = new principal.MaterialButton();
        btnVender = new principal.MaterialButton();
        quitar = new principal.MaterialButton();
        btnedit = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 111, 177));
        jPanel2.setForeground(new java.awt.Color(12, 140, 143));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/caja.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Caja");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(thishide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(thishide, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.setLayout(new java.awt.CardLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(769, 582));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laboratory_64.png"))); // NOI18N
        jLabel7.setText("Laboratorio");

        pnlChange.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        c_search_tbl.setBackground(new java.awt.Color(204, 204, 204));
        c_search_tbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c_search_tbl.setForeground(new java.awt.Color(0, 0, 0));
        c_search_tbl.setToolTipText("");
        c_search_tbl.setCaretColor(new java.awt.Color(0, 0, 0));
        c_search_tbl.setFocusCycleRoot(true);
        c_search_tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c_search_tbl.setInheritsPopupMenu(true);
        c_search_tbl.setPlaceholder("Buscar Nombre");
        c_search_tbl.setPreferredSize(new java.awt.Dimension(300, 32));
        c_search_tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_search_tblActionPerformed(evt);
            }
        });
        c_search_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_search_tblKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 296, 0, 0);
        jPanel5.add(c_search_tbl, gridBagConstraints);

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setToolTipText("");
        fecha.setDateFormatString("dd/MM/yyyy");
        fecha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        fecha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fecha.setPreferredSize(new java.awt.Dimension(170, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 18, 0, 0);
        jPanel5.add(fecha, gridBagConstraints);

        buscF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buscF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja/buscaF1.png"))); // NOI18N
        buscF.setToolTipText("Buscar");
        buscF.setBorder(null);
        buscF.setBorderPainted(false);
        buscF.setContentAreaFilled(false);
        buscF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscF.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja/buscaF2.png"))); // NOI18N
        buscF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 327);
        jPanel5.add(buscF, gridBagConstraints);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableCaja.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Domicilio", "Telefono"
            }
        ));
        tableCaja.setGridColor(new java.awt.Color(255, 255, 255));
        tableCaja.setRowHeight(20);
        tableCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCajaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCaja);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        btnsalestoday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sales_today_32.png"))); // NOI18N
        btnsalestoday.setText("Ventas de Hoy");
        btnsalestoday.setToolTipText("");
        btnsalestoday.setColorBorde(null);
        btnsalestoday.setColorHover(new java.awt.Color(12, 140, 143));
        btnsalestoday.setColorPressed(new java.awt.Color(12, 140, 143));
        btnsalestoday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsalestoday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsalestoday.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnsalestoday.setIconTextGap(19);
        btnsalestoday.setPreferredSize(new java.awt.Dimension(231, 32));
        btnsalestoday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalestodayMouseClicked(evt);
            }
        });
        btnsalestoday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalestodayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 239, 0, 0);
        jPanel12.add(btnsalestoday, gridBagConstraints);

        btnallsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_all_32.png"))); // NOI18N
        btnallsales.setText("Todas las Ventas");
        btnallsales.setToolTipText("");
        btnallsales.setColorBorde(null);
        btnallsales.setColorHover(new java.awt.Color(12, 140, 143));
        btnallsales.setColorPressed(new java.awt.Color(12, 140, 143));
        btnallsales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnallsales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnallsales.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnallsales.setIconTextGap(19);
        btnallsales.setPreferredSize(new java.awt.Dimension(231, 32));
        btnallsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnallsalesMouseClicked(evt);
            }
        });
        btnallsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallsalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanel12.add(btnallsales, gridBagConstraints);

        btnrecievable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receivable_32.png"))); // NOI18N
        btnrecievable.setText("Cuentas por Cobrar");
        btnrecievable.setToolTipText("");
        btnrecievable.setColorBorde(null);
        btnrecievable.setColorHover(new java.awt.Color(12, 140, 143));
        btnrecievable.setColorPressed(new java.awt.Color(12, 140, 143));
        btnrecievable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnrecievable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnrecievable.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnrecievable.setIconTextGap(19);
        btnrecievable.setPreferredSize(new java.awt.Dimension(210, 32));
        btnrecievable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrecievableMouseClicked(evt);
            }
        });
        btnrecievable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecievableActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 226);
        jPanel12.add(btnrecievable, gridBagConstraints);

        javax.swing.GroupLayout pnlChangeLayout = new javax.swing.GroupLayout(pnlChange);
        pnlChange.setLayout(pnlChangeLayout);
        pnlChangeLayout.setHorizontalGroup(
            pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChangeLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1)
                    .addGap(5, 5, 5)))
        );
        pnlChangeLayout.setVerticalGroup(
            pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeLayout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        txttotalcaja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotalcaja.setForeground(new java.awt.Color(0, 0, 0));
        txttotalcaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttotalcaja.setText("TOTAL A PAGAR: L");
        txttotalcaja.setToolTipText("");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txttotalcaja, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(562, Short.MAX_VALUE)
                    .addComponent(txttotalcaja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel10.add(jPanel11, "card2");

        jTabbedPane2.addTab("RegistroVentas", jPanel10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(769, 582));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 128, 131));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laboratory_64.png"))); // NOI18N
        jLabel14.setText("Laboratorio");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 111, 177));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NO. VENTA");

        numFac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numFac.setForeground(new java.awt.Color(0, 111, 177));
        numFac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numFac.setText("NO. VENTA");

        rbcontado.setBackground(new java.awt.Color(255, 255, 255));
        selectestado.add(rbcontado);
        rbcontado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbcontado.setForeground(new java.awt.Color(0, 0, 0));
        rbcontado.setText("CONTADO");
        rbcontado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcontadoActionPerformed(evt);
            }
        });

        rbcredito.setBackground(new java.awt.Color(255, 255, 255));
        selectestado.add(rbcredito);
        rbcredito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbcredito.setForeground(new java.awt.Color(0, 0, 0));
        rbcredito.setText("CRÉDITO");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(numFac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(rbcontado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbcredito)))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numFac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcredito)
                    .addComponent(rbcontado))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImporte.setBorder(null);
        txtImporte.setForeground(new java.awt.Color(58, 159, 171));
        txtImporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtImporte.setPlaceholder("IMPORTE");
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });
        jPanel8.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-importe.png"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));

        txtCambio.setEditable(false);
        txtCambio.setBorder(null);
        txtCambio.setForeground(new java.awt.Color(58, 159, 171));
        txtCambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCambio.setPlaceholder("CAMBIO");
        txtCambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCambioKeyTyped(evt);
            }
        });
        jPanel8.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-cambio.png"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/calculator.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("");
        btnCalcular.setColorHover(new java.awt.Color(12, 140, 143));
        btnCalcular.setColorPressed(new java.awt.Color(12, 140, 143));
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.setIconTextGap(10);
        btnCalcular.setPreferredSize(new java.awt.Dimension(150, 32));
        btnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCalcularMousePressed(evt);
            }
        });
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel8.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpaciente.setEditable(false);
        txtpaciente.setBorder(null);
        txtpaciente.setForeground(new java.awt.Color(58, 159, 171));
        txtpaciente.setText("PACIENTE ATENDIDO");
        txtpaciente.setToolTipText("");
        txtpaciente.setEnabled(false);
        txtpaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpaciente.setPlaceholder("PACIENTE ATENDIDO");
        jPanel4.add(txtpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-cliente.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        txtFecha.setBorder(null);
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFecha.setPlaceholder("FECHA");
        jPanel4.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 240, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-calendario.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        btnVender1.setBackground(new java.awt.Color(0, 111, 177));
        btnVender1.setForeground(new java.awt.Color(255, 255, 255));
        btnVender1.setText("BUSCAR PRODUCTOS");
        btnVender1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVender1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnVender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 261, 48));

        jSeparator1.setBackground(new java.awt.Color(58, 159, 171));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 12, 10, 200));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/HODUMEDIC_1.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 160));

        btnservicios.setBackground(new java.awt.Color(0, 111, 177));
        btnservicios.setForeground(new java.awt.Color(255, 255, 255));
        btnservicios.setText("BUSCAR SERVICIOS");
        btnservicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnservicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserviciosActionPerformed(evt);
            }
        });
        jPanel4.add(btnservicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 258, 48));

        btnservicios1.setBackground(new java.awt.Color(0, 111, 177));
        btnservicios1.setBorder(null);
        btnservicios1.setForeground(new java.awt.Color(255, 255, 255));
        btnservicios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_caja.png"))); // NOI18N
        btnservicios1.setText("buscar");
        btnservicios1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnservicios1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnservicios1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnservicios1.setRippleColor(new java.awt.Color(60, 63, 65));
        btnservicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnservicios1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnservicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 80, 50));

        isv.setBorder(null);
        isv.setForeground(new java.awt.Color(0, 0, 0));
        isv.setText("15");
        isv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        isv.setPlaceholder("ISV");
        jPanel4.add(isv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-isv.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 310, -1));

        jPanel7.setBackground(new java.awt.Color(0, 111, 177));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));

        tablaCaja.setBackground(new java.awt.Color(0, 0, 0));
        tablaCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaCaja.setForeground(new java.awt.Color(255, 255, 255));
        tablaCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUCTO / SERVICIO", "PRECIO (L)", "CANTIDAD", "IMPORTE (L)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCaja.setDoubleBuffered(true);
        tablaCaja.setRowHeight(20);
        tablaCaja.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaCaja.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaCaja);

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        txttotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttotal.setText("TOTAL A PAGAR: L");
        txttotal.setToolTipText("");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0.0");

        txtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsubtotal.setForeground(new java.awt.Color(255, 255, 255));
        txtsubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtsubtotal.setText("SUBTOTAL: L ");

        lblsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsubtotal.setForeground(new java.awt.Color(255, 255, 255));
        lblsubtotal.setText("0.0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel6.setBorder(dropShadowBorder2);

        btnCancelar.setBackground(new java.awt.Color(0, 111, 177));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Canclar la ventar</h4> </body> </html>");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVender.setBackground(new java.awt.Color(0, 111, 177));
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("REALIZAR VENTA");
        btnVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        quitar.setBackground(new java.awt.Color(0, 111, 177));
        quitar.setForeground(new java.awt.Color(255, 255, 255));
        quitar.setText("QUITAR");
        quitar.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Quitar</h4> </body> </html>");
        quitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(0, 111, 177));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Actualizar");
        btnedit.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Quitar</h4> </body> </html>");
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(quitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nuevo Factura", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Registro de Ventas");

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String Estado_actual;
    private void numeros() {
        int j;
        int cont = 1;
        String num = "";
        String c = "";
        String SQL = "SELECT MAX(idventa) FROM caja_laboratorio";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            if (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                numFac.setText("00000001");
            } else {
                j = Integer.parseInt(c);
                GenerarNumero gen = new GenerarNumero();
                gen.generar(j);
                numFac.setText(gen.serie());

            }

        } catch (SQLException ex) {
//           Logger.getLogger(opciones_laboratorioVen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);

    }

    void limpiaCampos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaCaja.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        Get_Data();
        rbcontado.setSelected(false);
        txtpaciente.setText("");
        rbcredito.setSelected(false);
        txtImporte.setText("");
        txtCambio.setText("");
        lblTotal.setText("0.0");
        txtFecha.setText(fechaactual());
        lblsubtotal.setText("0.0");
        selectestado.clearSelection();
        btnedit.setVisible(false);
        this.rbcredito.setEnabled(true);
        numeros();
    }
  private void Get_Data(){
        thishide.setVisible(false);
        String sql="select idventa as 'Codigo',isv as 'ISV', paciente as 'Paciente', fecha as 'Fecha',estado_pago as 'Estado de Pago',total as 'Total (L)' from caja_laboratorio where estado_pago='Contado'";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tableCaja.setModel(DbUtils.resultSetToTableModel(rs));
         tableCaja.removeColumn(tableCaja.getColumnModel().getColumn(0));
         tableCaja.removeColumn(tableCaja.getColumnModel().getColumn(0));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          } 
        String pre;
        String can;
        double total = 0;
        float cantidad;

        for (int i = 0; i < tableCaja.getRowCount(); i++) {
            can = tableCaja.getValueAt(i, 3).toString();
            cantidad = Float.parseFloat(can);
            total = total + cantidad;
        }
        cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL EN CAJA: L " + Math.rint((total) * 100) / 100);
  }
  void cuentas_cobrar(){
        thishide.setVisible(true);
        String sql="select idventa as 'Codigo',isv as 'ISV', paciente as 'Paciente', fecha as 'Fecha',estado_pago as 'Estado de Pago',total as 'Total (L)' from caja_laboratorio where estado_pago='Crédito'";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tableCaja.setModel(DbUtils.resultSetToTableModel(rs));
         tableCaja.removeColumn(tableCaja.getColumnModel().getColumn(0));
         tableCaja.removeColumn(tableCaja.getColumnModel().getColumn(0));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);        
}       
        String can;
        double total = 0;
        float cantidad;

        for (int i = 0; i < tableCaja.getRowCount(); i++) {
            can = tableCaja.getValueAt(i, 3).toString();
            cantidad = Float.parseFloat(can);
            total = total + cantidad;
        }
        cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL POR COBRAR: L " + Math.rint((total) * 100) / 100);
}
private String condiciones(String estado_actual){
    if (rbcontado.isSelected()){
        estado_actual="Contado";
        }else if(rbcredito.isSelected()){
        estado_actual="Crédito";
     }else{
       estado_actual="vacio";
        }
        return estado_actual;
}
private void condicion(){
            String estado= tableCaja.getModel().getValueAt(tableCaja.getSelectedRow(), 4).toString();
            if ("Contado".equals(estado)){
               rbcontado.setSelected(true);
               rbcredito.setEnabled(false);
               btnedit.setEnabled(false);
               btnCancelar.setText("LIMPIAR");
                }else {
                rbcredito.setSelected(true);
             } 
}
    void actualizarStock() {
        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            Producto pr = new Producto();
            idp = tablaCaja.getValueAt(i, 0).toString();
            cant = Integer.parseInt(tablaCaja.getValueAt(i, 3).toString());
            pr = pdao.listarID(idp);
            int sa = pr.getStock() - cant;
            pdao.actualizarStock(sa, idp);

        }
    }
//    paciente,num_fac,estado,fecha,isv,codigo,nombre_p, precio, cantidad,importe, subtotal, total
    void print_bill(){
        laboratorio em;// Instaciamos la clase empleado
        List <laboratorio>lista = new ArrayList<>(); //Creamos una lista de empleados con ArrayList para obtener cada empleado
        for(int i=0; i<tablaCaja.getRowCount(); i++){ // Iterena cada fila de la tabla
            em = new laboratorio(txtpaciente.getText(),numFac.getText(),condiciones(Estado_actual), txtFecha.getText(),isv.getText(),tablaCaja.getValueAt(i, 0).toString(),tablaCaja.getValueAt(i,1).toString(), //Tomamos de la tabla el valor de cada columna y creamos un objeto empleado
            tablaCaja.getValueAt(i, 2).toString(),tablaCaja.getValueAt(i, 3).toString(),tablaCaja.getValueAt(i, 4).toString(),lblsubtotal.getText(),lblTotal.getText());
            lista.add(em); //Agregamos el objeto empleado a la lista
        }
        JasperReport reporte; // Instaciamos el objeto reporte
        String path = "src\\reportes\\caja_laboratorio.jasper"; //Ponemos la localizacion del reporte creado
        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Se carga el reporte de su localizacion
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(lista)); //Agregamos los parametros para llenar el reporte
            JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reportes
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Se declara con dispose_on_close para que no se cierre el programa cuando se cierre el reporte
            viewer.setVisible(true); //Se vizualiza el reporte
        } catch (JRException ex) {
           
        } 
}
    void sales_today(){
        thishide.setVisible(false);
        Date sistemaFech = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fecH = formato.format(sistemaFech);
       try {

            DefaultTableModel dt = (DefaultTableModel) tableCaja.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();

            ResultSet rs = s.executeQuery("SELECT * FROM caja_laboratorio WHERE fecha ='" + fecH + "' and estado_pago='Contado'");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                dt.addRow(v);
        String can;
        double total = 0;
        float cantidad;

        for (int i = 0; i < tableCaja.getRowCount(); i++) {
            can = tableCaja.getValueAt(i, 3).toString();
            cantidad = Float.parseFloat(can);
            total = total + cantidad;
        }
        cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL: L " + Math.rint((total) * 100) / 100);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }          
    }
    void sales_date(){
            String formato = fecha.getDateFormatString();
            Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato); 
            String fecH = (String.valueOf(sdf.format(date)));

       try {

            DefaultTableModel dt = (DefaultTableModel) tableCaja.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();

            ResultSet rs = s.executeQuery("SELECT * FROM caja_laboratorio WHERE fecha ='" + fecH + "' and estado_pago='Contado'");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                dt.addRow(v);
        String can;
        double total = 0;
        float cantidad;

        for (int i = 0; i < tableCaja.getRowCount(); i++) {
            can = tableCaja.getValueAt(i, 3).toString();
            cantidad = Float.parseFloat(can);
            total = total + cantidad;
        }
        cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL: L " + Math.rint((total) * 100) / 100);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }          
    }
    void receivable_date(){
            String formato = fecha.getDateFormatString();
            Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato); 
            String fecH = (String.valueOf(sdf.format(date)));

       try {

            DefaultTableModel dt = (DefaultTableModel) tableCaja.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();

            ResultSet rs = s.executeQuery("SELECT * FROM caja_laboratorio WHERE fecha ='" + fecH + "' and estado_pago='Crédito'");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                dt.addRow(v);
        String can;
        double total = 0;
        float cantidad;

        for (int i = 0; i < tableCaja.getRowCount(); i++) {
            can = tableCaja.getValueAt(i, 3).toString();
            cantidad = Float.parseFloat(can);
            total = total + cantidad;
        }
        cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL: L " + Math.rint((total) * 100) / 100);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }          
    }
    void cancel_edit(){
           this.quitar.setEnabled(true);
            this.btnservicios.setEnabled(true);
            this.btnVender.setEnabled(true);
            this.btnVender1.setEnabled(true);
            this.btnedit.setVisible(false);
            this.btnservicios1.setEnabled(true);
            this.btnedit.setEnabled(true);
            this.rbcredito.setEnabled(true);
            this.btnCancelar.setText("CANCELAR");
            isv.setEnabled(true);
            limpiaCampos();
            this.jTabbedPane2.setSelectedIndex(0);    
    }
    private void ingresar_detalle(){
    for (int i = 0; i <tablaCaja.getRowCount(); i++) {
        String codigo= tablaCaja.getModel().getValueAt(i, 0).toString();
        String p_s= tablaCaja.getModel().getValueAt(i, 1).toString();
        String precio= tablaCaja.getModel().getValueAt(i, 2).toString();
        String cantidad= tablaCaja.getModel().getValueAt(i, 3).toString();
        String importe= tablaCaja.getModel().getValueAt(i, 4).toString();
        String sql= "insert into detalle_laboratorio(idventa,codigo,p_s,precio,cantidad,importe) values ('"+numFac.getText()+"','" +codigo+"','" + p_s +"','" +precio+"','" +cantidad+"','" +importe+ "')";

        try{
            con=Conexion.ConnectDB();
            pst=con.prepareStatement(sql);
            pst.execute();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }
         }
    private void show_detalle(){
        String sql="select codigo as 'Codigo',p_s as 'Prodcuto/Servicio',precio as 'Precio',cantidad as 'Cantidad',importe as 'Importe' from detalle_laboratorio where idventa='" + numFac.getText() + "' ";
        try{
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         tablaCaja.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}    
    }
    void subtotal(){
        String pre;
        String can;
        double total = 0;
        double precio;
        int cantidad;
        double imp = 0.0;

        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            pre = tablaCaja.getValueAt(i, 2).toString();
            can = tablaCaja.getValueAt(i, 3).toString();
            precio = Double.parseDouble(pre);
            cantidad = Integer.parseInt(can);
            imp = precio * cantidad;
            total = total + imp;
        }
        cajaservicios.caja_laboratorio.lblsubtotal.setText("" + Math.rint((total) * 100) / 100);
    }
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void c_search_tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_search_tblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_search_tblActionPerformed

    private void c_search_tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_search_tblKeyReleased
        // search btn code
        String name = c_search_tbl.getText();
        try {

            DefaultTableModel dt = (DefaultTableModel) tableCaja.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();
            if (thishide.isVisible()){
                ResultSet rs = s.executeQuery("SELECT * FROM caja_laboratorio WHERE paciente LIKE '%"+name+"%' and estado_pago='Crédito'");

                    while (rs.next()) {
                        Vector v = new Vector();
                        v.add(rs.getString(1));
                        v.add(rs.getString(2));
                        v.add(rs.getString(3));
                        v.add(rs.getString(4));
                        v.add(rs.getString(5));
                        v.add(rs.getString(6));
                        dt.addRow(v);
                String can;
                double total = 0;
                float cantidad;

                for (int i = 0; i < tableCaja.getRowCount(); i++) {
                    can = tableCaja.getValueAt(i, 3).toString();
                    cantidad = Float.parseFloat(can);
                    total = total + cantidad;
                }
                cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL: L " + Math.rint((total) * 100) / 100);
                    }
              }else {
                    ResultSet rs = s.executeQuery("SELECT * FROM caja_laboratorio WHERE paciente LIKE '%"+name+"%' and estado_pago='Contado'");

                    while (rs.next()) {
                        Vector v = new Vector();
                        v.add(rs.getString(1));
                        v.add(rs.getString(2));
                        v.add(rs.getString(3));
                        v.add(rs.getString(4));
                        v.add(rs.getString(5));
                        v.add(rs.getString(6));
                        dt.addRow(v);
                String can;
                double total = 0;
                float cantidad;

                for (int i = 0; i < tableCaja.getRowCount(); i++) {
                    can = tableCaja.getValueAt(i, 3).toString();
                    cantidad = Float.parseFloat(can);
                    total = total + cantidad;
                }
                cajaservicios.caja_laboratorio.txttotalcaja.setText("TOTAL: L " + Math.rint((total) * 100) / 100);
                    }
        }


        } catch (Exception e) {
            Get_Data();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_c_search_tblKeyReleased
    //select idventa as 'Codigo',isv as 'ISV', paciente as 'Paciente', fecha as 'Fecha',estado_pago as 'Estado de Pago',total as 'Total (L)'
    private void tableCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCajaMouseClicked
        try {
            int row= tableCaja.getSelectedRow();
            numFac.setText(tableCaja.getModel().getValueAt(row,0).toString());
            isv.setText(tableCaja.getModel().getValueAt(row,1).toString());
            txtpaciente.setText(tableCaja.getModel().getValueAt(row,2).toString());
            lblTotal.setText(tableCaja.getModel().getValueAt(row,5).toString());
            txtFecha.setText(tableCaja.getModel().getValueAt(row,3).toString()) ;
            condicion();
            isv.setEnabled(false);
            txttotal.setText("TOTAL PAGADO: L");
            this.quitar.setEnabled(false);
            this.btnservicios.setEnabled(false);
            this.btnVender.setEnabled(false);
            this.btnVender1.setEnabled(false);
            this.btnedit.setVisible(true);
            this.btnservicios1.setEnabled(false);
            this.jTabbedPane2.setSelectedIndex(1);
            show_detalle();
            subtotal();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableCajaMouseClicked

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtImporteKeyTyped

    private void txtCambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCambioKeyTyped

    }//GEN-LAST:event_txtCambioKeyTyped

    private void btnVender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender1ActionPerformed
        new lista_productos_servicios.productos_laboratorio(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnVender1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (btnedit.isVisible()){
            cancel_edit();
        }else{
        limpiaCampos();
        producto.Opciones.cancelarTransaccion();}
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if (this.tablaCaja.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("IMPOSIBLE REALIZAR");
            er.msj1.setText("LA VENTA");
            er.setVisible(true);
        } else {
        try{
            con=Conexion.ConnectDB();
            if (txtpaciente.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Paciente","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtFecha.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Fecha","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        if("vacio".equals(condiciones(Estado_actual))){
                JOptionPane.showMessageDialog( this, "Seleccione Si es al Crédito o al Contado","Error", JOptionPane.ERROR_MESSAGE);
                rbcontado.requestFocus();
                return;
            }
               // insertar datos en caja_laboratorio
            String sql= "insert into caja_laboratorio(idventa,isv,paciente,total,fecha,estado_pago) values ('"+numFac.getText()+"','" +isv.getText()+"','" +txtpaciente.getText()+"','" + lblTotal.getText() +"','" +txtFecha.getText()+"','" +condiciones(Estado_actual)+ "')";
            pst=con.prepareStatement(sql);
            pst.execute();
            actualizarStock(); 
            ingresar_detalle();
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            sa.titulo.setText("¡HECHO!");
            sa.msj.setText("VENTA REALIZADA CON");
            sa.msj1.setText("ÉXITO");
            sa.setVisible(true);
            print_bill();
            this.jTabbedPane2.setSelectedIndex(0);
            limpiaCampos();
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        } 
        }
    }//GEN-LAST:event_btnVenderActionPerformed
    public static void calcular() {
        String pre;
        String can;
        double total = 0;
        double precio;
        int cantidad;
        double imp = 0.0;

        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            pre = tablaCaja.getValueAt(i, 2).toString();
            can = tablaCaja.getValueAt(i, 3).toString();
            precio = Double.parseDouble(pre);
            cantidad = Integer.parseInt(can);
            imp = precio * cantidad;
            total = total + imp;
            tablaCaja.setValueAt(Math.rint(imp * 100) / 100, i, 4);

        }
        lblTotal.setText("" + Math.rint(total * 100) / 100);
    }
    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCaja.getModel();
        if (modelo.getRowCount() > 0) {

            int fila = this.tablaCaja.getSelectedRow();
            if (this.tablaCaja.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                modelo.removeRow(fila);
                calcular();
            }
        }
    }//GEN-LAST:event_quitarActionPerformed

    private void btnserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserviciosActionPerformed
        new lista_servicios.lista_laboratorio(new JFrame(), true).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnserviciosActionPerformed

    private void btnservicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnservicios1ActionPerformed
        new pacientes.lista_pacientes_laboratorio(new JFrame(), true).setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btnservicios1ActionPerformed

    private void rbcontadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcontadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcontadoActionPerformed

    private void btnCalcularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMousePressed

    }//GEN-LAST:event_btnCalcularMousePressed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (this.txtImporte.getText().equals("") || this.txtImporte.getText().equals("0") ) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("DEBES INGRESAR UNA");
                er.msj1.setText("CANTIDAD");
                er.setVisible(true);
            } else {
                float recibe = Float.parseFloat(txtImporte.getText());
                float total = Float.parseFloat(lblTotal.getText());

                if (total > 0.0) {
                    if (recibe > total) {
                        float cambio = recibe-total;
                        txtCambio.setText(String.valueOf(cambio));
                    } else {
                        ErrorAlert er = new ErrorAlert(new JFrame(), true);
                        er.titulo.setText("OOPS...");
                        er.msj.setText("INGRESA UNA CANTIDAD");
                        er.msj1.setText("VALIDA");
                        er.setVisible(true);
                    }
                } else {
                    ErrorAlert er = new ErrorAlert(new JFrame(), true);
                    er.titulo.setText("OOPS...");
                    er.msj.setText("IMPOSIBLE REALIZAR");
                    er.msj1.setText("LA OPERACIÓN");
                    er.setVisible(true);
                }
            }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if("Crédito".equals(condiciones(Estado_actual))){
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("NO SE HA HECHO");
            er.msj1.setText("CAMBIOS");
            er.setVisible(true);
        }else{
        try{
            con=Conexion.ConnectDB();
            String sql= "update caja_laboratorio set estado_pago='" + condiciones(Estado_actual) + "' where idventa='" + numFac.getText()+ "'";
            pst=con.prepareStatement(sql);
            pst.execute();
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            sa.titulo.setText("¡HECHO!");
            sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
            sa.msj1.setText("");
            sa.setVisible(true);
            print_bill();
            cancel_edit();

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        } }         // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsalestodayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalestodayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalestodayMouseClicked

    private void btnsalestodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalestodayActionPerformed
        sales_today();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalestodayActionPerformed

    private void btnallsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnallsalesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnallsalesMouseClicked

    private void btnallsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallsalesActionPerformed
        Get_Data();        // TODO add your handling code here:
    }//GEN-LAST:event_btnallsalesActionPerformed

    private void btnrecievableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrecievableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecievableMouseClicked

    private void btnrecievableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecievableActionPerformed
        cuentas_cobrar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecievableActionPerformed

    private void buscFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscFActionPerformed
            if (thishide.isVisible()){
                receivable_date();
                }else {
            sales_date();
        }
       
    }//GEN-LAST:event_buscFActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rsbuttom.RSButtonMetro btnCalcular;
    private principal.MaterialButton btnCancelar;
    private principal.MaterialButton btnVender;
    private principal.MaterialButton btnVender1;
    private rsbuttom.RSButtonMetro btnallsales;
    private principal.MaterialButton btnedit;
    private rsbuttom.RSButtonMetro btnrecievable;
    private rsbuttom.RSButtonMetro btnsalestoday;
    private principal.MaterialButton btnservicios;
    private principal.MaterialButton btnservicios1;
    private javax.swing.JButton buscF;
    private app.bolivia.swing.JCTextField c_search_tbl;
    private principal.MaterialButton cerrar;
    public com.toedter.calendar.JDateChooser fecha;
    public static app.bolivia.swing.JCTextField isv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JLabel lblTotal;
    public static javax.swing.JLabel lblsubtotal;
    public static javax.swing.JLabel numFac;
    private javax.swing.JPanel pnlChange;
    private principal.MaterialButton quitar;
    private javax.swing.JRadioButton rbcontado;
    private javax.swing.JRadioButton rbcredito;
    private javax.swing.ButtonGroup selectestado;
    public static javax.swing.JTable tablaCaja;
    private javax.swing.JTable tableCaja;
    private javax.swing.JLabel thishide;
    public static app.bolivia.swing.JCTextField txtCambio;
    private app.bolivia.swing.JCTextField txtFecha;
    public static app.bolivia.swing.JCTextField txtImporte;
    public static app.bolivia.swing.JCTextField txtpaciente;
    private javax.swing.JLabel txtsubtotal;
    private javax.swing.JLabel txttotal;
    private static javax.swing.JLabel txttotalcaja;
    // End of variables declaration//GEN-END:variables
}
