/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidad;
import alertas.principal.SuccessAlert;
import cafeteria.OpcionesAl;
import java.awt.HeadlessException;
import paneles.*;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import principal.GenerarNumero;
import principal.PrincipalAdministrador;
import static principal.PrincipalAdministrador.escritorio;
import static principal.PrincipalAdministrador.estacerrado;
import static principal.PrincipalAdministrador.menu;
/**
 *
 * @author Rojeru San
 */
public class estado_resultados_rayosx extends javax.swing.JInternalFrame {
SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
Connection con=null;
public PrincipalAdministrador a ;
Date dato = null;
ResultSet rs=null;
PreparedStatement pst=null;
    static Conexion cc = new Conexion();
    static Connection cn = cc.ConnectDB();
    static PreparedStatement ps;
    /**
     * Creates new form NewJInternalFrame
     */
    public estado_resultados_rayosx() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        con= Conexion.ConnectDB();
        nuevo();
        txttotalingresos.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        registrar = new principal.MaterialButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlingresos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtingnetos = new java.awt.TextField();
        txtdescuento = new java.awt.TextField();
        txttotalingresos = new java.awt.TextField();
        jLabel16 = new javax.swing.JLabel();
        numFac = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlegresos = new javax.swing.JPanel();
        txtpublicidad = new java.awt.TextField();
        txtimpuestos = new java.awt.TextField();
        txtsueysa = new java.awt.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txttotaloperacion = new java.awt.TextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtotrosgastos = new java.awt.TextField();
        pnlegresos1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtpapeleria = new java.awt.TextField();
        txtdepremoviliario = new java.awt.TextField();
        txtdepreequimedico = new java.awt.TextField();
        txtutilidad = new java.awt.TextField();
        txttotalegresos = new java.awt.TextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtdeprevehiculos = new java.awt.TextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtotrodgastosadmon = new java.awt.TextField();
        jLabel46 = new javax.swing.JLabel();
        txttotsladmon = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnimprimir = new principal.MaterialButtomRectangle();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 111, 177));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setForeground(new java.awt.Color(58, 159, 171));
        registrar.setText("reportes anteriores");
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrarKeyTyped(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/previous_48.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ingresos ");

        pnlingresos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total Ingresos en RayosX:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descuentos:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ingresos Netos:");

        txtingnetos.setEnabled(false);
        txtingnetos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtingnetos.setText("0");

        txtdescuento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtdescuento.setText("0");
        txtdescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdescuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescuentoKeyTyped(evt);
            }
        });

        txttotalingresos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttotalingresos.setText("0");
        txttotalingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalingresosActionPerformed(evt);
            }
        });
        txttotalingresos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttotalingresosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotalingresosKeyTyped(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Número:");

        numFac.setBackground(new java.awt.Color(0, 0, 0));
        numFac.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numFac.setForeground(new java.awt.Color(0, 0, 0));
        numFac.setText("Numero");

        javax.swing.GroupLayout pnlingresosLayout = new javax.swing.GroupLayout(pnlingresos);
        pnlingresos.setLayout(pnlingresosLayout);
        pnlingresosLayout.setHorizontalGroup(
            pnlingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlingresosLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(numFac))
            .addGroup(pnlingresosLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(txttotalingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlingresosLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlingresosLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(txtingnetos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlingresosLayout.setVerticalGroup(
            pnlingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlingresosLayout.createSequentialGroup()
                .addGroup(pnlingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(numFac))
                .addGap(10, 10, 10)
                .addGroup(pnlingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txttotalingresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtingnetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(128, 128, 131));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Egresos");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(128, 128, 131));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Estado de Resultados");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(128, 128, 131));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("     Gastos de Operación                                                Gastos de Administración");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        pnlegresos.setBackground(new java.awt.Color(255, 255, 255));

        txtpublicidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtpublicidad.setText("0");
        txtpublicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpublicidadActionPerformed(evt);
            }
        });
        txtpublicidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpublicidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpublicidadKeyTyped(evt);
            }
        });

        txtimpuestos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtimpuestos.setText("0");
        txtimpuestos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtimpuestosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimpuestosKeyTyped(evt);
            }
        });

        txtsueysa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtsueysa.setText("0");
        txtsueysa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsueysaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsueysaKeyTyped(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Utilidad del período:");

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Publicidad:");

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Sueldos y salarios:");

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Impuestos:");

        txttotaloperacion.setEnabled(false);
        txttotaloperacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttotaloperacion.setName(""); // NOI18N
        txttotaloperacion.setText("0");

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Total Gastos de Operacion: ");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Otros gastos:");

        txtotrosgastos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtotrosgastos.setText("0");
        txtotrosgastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtotrosgastosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtotrosgastosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlegresosLayout = new javax.swing.GroupLayout(pnlegresos);
        pnlegresos.setLayout(pnlegresosLayout);
        pnlegresosLayout.setHorizontalGroup(
            pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlegresosLayout.createSequentialGroup()
                .addGroup(pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addComponent(txtpublicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26)
                        .addComponent(txtsueysa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel19)
                        .addGap(26, 26, 26)
                        .addComponent(txtimpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel24)
                        .addGap(26, 26, 26)
                        .addComponent(txtotrosgastos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel23)
                        .addGap(26, 26, 26)
                        .addComponent(txttotaloperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlegresosLayout.setVerticalGroup(
            pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlegresosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtpublicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsueysa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)))
                .addGap(10, 10, 10)
                .addGroup(pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtimpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlegresosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19)))
                .addGap(16, 16, 16)
                .addGroup(pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtotrosgastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlegresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txttotaloperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(jLabel15))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -149;
        gridBagConstraints.ipady = -17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        jPanel4.add(pnlegresos, gridBagConstraints);

        pnlegresos1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Papeleria: ");

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Depreciación de equipo médico:");

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Depreciación de vehiculos:");

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Total de Egresos:");

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Utilidad del período:");

        txtpapeleria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtpapeleria.setText("0");
        txtpapeleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpapeleriaActionPerformed(evt);
            }
        });
        txtpapeleria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpapeleriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpapeleriaKeyTyped(evt);
            }
        });

        txtdepremoviliario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtdepremoviliario.setText("0");
        txtdepremoviliario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdepremoviliarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdepremoviliarioKeyTyped(evt);
            }
        });

        txtdepreequimedico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtdepreequimedico.setText("0");
        txtdepreequimedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepreequimedicoActionPerformed(evt);
            }
        });
        txtdepreequimedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdepreequimedicoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdepreequimedicoKeyTyped(evt);
            }
        });

        txtutilidad.setEnabled(false);
        txtutilidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtutilidad.setName(""); // NOI18N
        txtutilidad.setText("0");

        txttotalegresos.setEnabled(false);
        txttotalegresos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttotalegresos.setName(""); // NOI18N
        txttotalegresos.setText("0");
        txttotalegresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalegresosActionPerformed(evt);
            }
        });

        txtdeprevehiculos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtdeprevehiculos.setText("0");
        txtdeprevehiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdeprevehiculosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdeprevehiculosKeyTyped(evt);
            }
        });

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Depreciación de Mobiliario:");

        jLabel45.setBackground(new java.awt.Color(0, 0, 0));
        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Otros gastos Admon:");

        txtotrodgastosadmon.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtotrodgastosadmon.setText("0");
        txtotrodgastosadmon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtotrodgastosadmonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtotrodgastosadmonKeyTyped(evt);
            }
        });

        jLabel46.setBackground(new java.awt.Color(0, 0, 0));
        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Total de Gastos de Administración:");

        txttotsladmon.setEnabled(false);
        txttotsladmon.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txttotsladmon.setName(""); // NOI18N
        txttotsladmon.setText("0");

        javax.swing.GroupLayout pnlegresos1Layout = new javax.swing.GroupLayout(pnlegresos1);
        pnlegresos1.setLayout(pnlegresos1Layout);
        pnlegresos1Layout.setHorizontalGroup(
            pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlegresos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel34)
                        .addGap(13, 13, 13)
                        .addComponent(txtpapeleria, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel36)
                        .addGap(10, 10, 10)
                        .addComponent(txtdeprevehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel35)
                        .addGap(10, 10, 10)
                        .addComponent(txtdepreequimedico, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel44)
                        .addGap(10, 10, 10)
                        .addComponent(txtdepremoviliario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel45)
                        .addGap(10, 10, 10)
                        .addComponent(txtotrodgastosadmon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(10, 10, 10)
                        .addComponent(txttotsladmon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel37)
                        .addGap(10, 10, 10)
                        .addComponent(txttotalegresos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel38)
                        .addGap(10, 10, 10)
                        .addComponent(txtutilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlegresos1Layout.setVerticalGroup(
            pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlegresos1Layout.createSequentialGroup()
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(txtpapeleria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdeprevehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdepreequimedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel35)))
                .addGap(16, 16, 16)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(txtdepremoviliario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(txtotrodgastosadmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel46))
                    .addComponent(txttotsladmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txttotalegresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlegresos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlegresos1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel38))
                    .addComponent(txtutilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanel4.add(pnlegresos1, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnimprimir.setBackground(new java.awt.Color(0, 111, 177));
        btnimprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimir.setText("guardar");
        btnimprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnimprimir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnimprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(17, 452, 0, 377);
        jPanel5.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlingresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlingresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void extraerID() {
        int j;
        int cont = 1;
        String num = "";
        String c = "";
        String SQL = "SELECT MAX(id) FROM estado_resultados_rayosx";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            if (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                numFac.setText("00000001");
            } else {
                j = Integer.parseInt(c);
                GenerarNumero gen = new GenerarNumero();
                gen.generar(j);
                numFac.setText(gen.serie());

            }

        } catch (SQLException ex) {
            Logger.getLogger(OpcionesAl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //no dejar en blanco las cajas de texto
    private void validar_ingreso(){
            if (txttotalingresos.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Total de Ingresos","Error", JOptionPane.ERROR_MESSAGE);
                txttotalingresos.requestFocus();
                return;
            }
            if (txtpublicidad.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Egresos por Publicidad","Error", JOptionPane.ERROR_MESSAGE);
                txtpublicidad.requestFocus();
                return;
            }
            if (txtsueysa.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Egresos por Sueldos y Salarios","Error", JOptionPane.ERROR_MESSAGE);
                txtsueysa.requestFocus();
                return;
            }if (txtimpuestos.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Egresos por Impuestos","Error", JOptionPane.ERROR_MESSAGE);
                txtimpuestos.requestFocus();
                return;
            }
            if (txtpapeleria.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Egresos Por Papelería","Error", JOptionPane.ERROR_MESSAGE);
                txtpapeleria.requestFocus();
                return;
            }if (txtdeprevehiculos.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Egresos por Depreciación de Vehículos","Error", JOptionPane.ERROR_MESSAGE);
                txtdeprevehiculos.requestFocus();
                return;
            }
            if (txtdepreequimedico.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Egresos por Depreciación de equipo Médico","Error", JOptionPane.ERROR_MESSAGE);
                txtdepreequimedico.requestFocus();
                return;
            }if (txtdepremoviliario.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Egresos por Depreciación de Mobiliario","Error", JOptionPane.ERROR_MESSAGE);
                txtdepremoviliario.requestFocus();
                return;
            }
            
    }
//funcion para obtener la fecha de hoy
      public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatofecha.format(fecha);

    }
        private void insert_data(){
        try{
            con=Conexion.ConnectDB();
            validar_ingreso();
               // insertar datos en la tabla estado_resultados_rayosx
            String sql= "insert into estado_resultados_rayosx(id,"
                    + "total_ingresos,"
                    + "descuentos,"
                    + "ingresos_netos,"
                    + "publicidad,"
                    + "sueldos_salarios,"
                    + "impuestos,"
                    + "otros_gastos_operacion,"
                    + "total_gastosoperacion,"
                    + "papeleria,"
                    + "depreciacion_vehiculos,"
                    + "depreciacion_medico,"
                    + "depreciacion_mobiliario,"
                    + "otros_gastos_admon,"
                    + "total_gastosadmon,"
                    + "total_egresos,"
                    + "utilidad,"
                    + "fecha) values ('"
                    +numFac.getText()+"','" 
                    +"','" + txttotalingresos.getText()
                    +"','" + txtdescuento.getText()
                    +"','" + txtingnetos.getText()
                    +"','" + txtpublicidad.getText()
                    +"','" + txtsueysa.getText()
                    +"','" + txtimpuestos.getText()
                    +"','" + txtotrosgastos.getText()
                    +"','" + txttotaloperacion.getText()
                    +"','" + txtpapeleria.getText()
                    +"','" + txtdeprevehiculos.getText()
                    +"','" + txtdepreequimedico.getText()
                    +"','" + txtdepremoviliario.getText()
                    +"','" + txtotrodgastosadmon.getText()
                    +"','" + txttotsladmon.getText()
                    +"','" + txttotalegresos.getText()
                    +"','" + txtutilidad.getText()
                    +"','" + fechaactual() + "')";
            pst=con.prepareStatement(sql);
            pst.execute();
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            sa.titulo.setText("¡HECHO!");
            sa.msj.setText("REGISTRADO");
            sa.msj1.setText("CON ÉXITO");
            sa.setVisible(true);
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        } 
  }
    //función para limpiar los campos del estado de resultados
    private void nuevo()
{
    numFac.setText("0");
     txttotalingresos.setText("0");
     txtdescuento.setText("0");
     txtingnetos.setText("0");
     txtpublicidad.setText("0");
     txtsueysa.setText("0");
     txtimpuestos.setText("0");
     txtotrosgastos.setText("0");
     txttotaloperacion.setText("0");
     txtpapeleria.setText("0");
     txtdeprevehiculos.setText("0");
     txtdepreequimedico.setText("0");
     txtdepremoviliario.setText("0");
     txtotrodgastosadmon.setText("0");
     txttotsladmon.setText("0");
     txttotalegresos.setText("0");
     txtutilidad.setText("0");    
    extraerID();
}
    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        validar_ingreso();
        insert_data();
        nuevo();
        //        print_bill();
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txttotalegresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalegresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalegresosActionPerformed

    private void txtpapeleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpapeleriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpapeleriaActionPerformed

    private void txtpublicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpublicidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpublicidadActionPerformed

    private void txttotalingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalingresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalingresosActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void txtdescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescuentoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtdescuentoKeyTyped

    private void txtdescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescuentoKeyReleased
        String numero=txtdescuento.getText();
        if(numero.equals("")==false){
            float ingreso_neto;
            ingreso_neto=(Float.parseFloat(txttotalingresos.getText())-Float.parseFloat(txtdescuento.getText()));
            String suma_ingresoneto= String.valueOf(ingreso_neto);
            txtingnetos.setText(suma_ingresoneto);
        }else
           txtdescuento.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtdescuentoKeyReleased

    private void txtpublicidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpublicidadKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtpublicidadKeyTyped

    private void txtsueysaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsueysaKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueysaKeyTyped

    private void txtimpuestosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimpuestosKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtimpuestosKeyTyped

    private void txtotrosgastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotrosgastosKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtotrosgastosKeyTyped

    private void txtpublicidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpublicidadKeyReleased
        String numero=txtpublicidad.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpublicidad.getText()) + Float.parseFloat(txtsueysa.getText())+
                  Float.parseFloat(txtimpuestos.getText())+Float.parseFloat(txtotrosgastos.getText()));
            String suma= String.valueOf(sum);
            txttotaloperacion.setText(suma);
        }else
           txtpublicidad.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_txtpublicidadKeyReleased

    private void txtsueysaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsueysaKeyReleased
        String numero=txtsueysa.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpublicidad.getText()) + Float.parseFloat(txtsueysa.getText())+
                  Float.parseFloat(txtimpuestos.getText())+Float.parseFloat(txtotrosgastos.getText()));
            String suma= String.valueOf(sum);
            txttotaloperacion.setText(suma);
        }else
           txtsueysa.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueysaKeyReleased

    private void txtimpuestosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimpuestosKeyReleased
        String numero=txtimpuestos.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpublicidad.getText()) + Float.parseFloat(txtsueysa.getText())+
                  Float.parseFloat(txtimpuestos.getText())+Float.parseFloat(txtotrosgastos.getText()));
            String suma= String.valueOf(sum);
            txttotaloperacion.setText(suma);
        }else
           txtimpuestos.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtimpuestosKeyReleased

    private void txtotrosgastosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotrosgastosKeyReleased
        String numero=txtotrosgastos.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpublicidad.getText()) + Float.parseFloat(txtsueysa.getText())+
                  Float.parseFloat(txtimpuestos.getText())+Float.parseFloat(txtotrosgastos.getText()));
            String suma= String.valueOf(sum);
            txttotaloperacion.setText(suma);
        }else
           txtotrosgastos.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtotrosgastosKeyReleased

    private void txtpapeleriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpapeleriaKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtpapeleriaKeyTyped

    private void txtdeprevehiculosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeprevehiculosKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeprevehiculosKeyTyped

    private void txtdepreequimedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepreequimedicoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepreequimedicoKeyTyped

    private void txtdepremoviliarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepremoviliarioKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepremoviliarioKeyTyped

    private void txtotrodgastosadmonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotrodgastosadmonKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtotrodgastosadmonKeyTyped

    private void txtpapeleriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpapeleriaKeyReleased
        String numero=txtpapeleria.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpapeleria.getText()) + Float.parseFloat(txtdeprevehiculos.getText())+
                  Float.parseFloat(txtdepreequimedico.getText())+Float.parseFloat(txtdepremoviliario.getText())+
                  Float.parseFloat(txtotrodgastosadmon.getText()));
            String suma= String.valueOf(sum);
            txttotsladmon.setText(suma);
            float sum_egresos;
            sum_egresos=(Float.parseFloat(txttotaloperacion.getText())+Float.parseFloat(txttotsladmon.getText()));
            String suma_egresos= String.valueOf(sum_egresos);
            txttotalegresos.setText(suma_egresos);
            float utilidad;
            utilidad=(Float.parseFloat(txtingnetos.getText())-Float.parseFloat(txttotalegresos.getText()));
            String utilida_neta= String.valueOf(utilidad);
            txtutilidad.setText(utilida_neta);
        }else
           txtpapeleria.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpapeleriaKeyReleased

    private void txtdeprevehiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeprevehiculosKeyReleased
        String numero=txtdeprevehiculos.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpapeleria.getText()) + Float.parseFloat(txtdeprevehiculos.getText())+
                  Float.parseFloat(txtdepreequimedico.getText())+Float.parseFloat(txtdepremoviliario.getText())+
                  Float.parseFloat(txtotrodgastosadmon.getText()));
            String suma= String.valueOf(sum);
            txttotsladmon.setText(suma);
            float sum_egresos;
            sum_egresos=(Float.parseFloat(txttotaloperacion.getText())+Float.parseFloat(txttotsladmon.getText()));
            String suma_egresos= String.valueOf(sum_egresos);
            txttotalegresos.setText(suma_egresos);
            float utilidad;
            utilidad=(Float.parseFloat(txtingnetos.getText())-Float.parseFloat(txttotalegresos.getText()));
            String utilida_neta= String.valueOf(utilidad);
            txtutilidad.setText(utilida_neta);
        }else
           txtdeprevehiculos.requestFocus();          // TODO add your handling code here:
    }//GEN-LAST:event_txtdeprevehiculosKeyReleased

    private void txtdepreequimedicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepreequimedicoKeyReleased
        String numero=txtdepreequimedico.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpapeleria.getText()) + Float.parseFloat(txtdeprevehiculos.getText())+
                  Float.parseFloat(txtdepreequimedico.getText())+Float.parseFloat(txtdepremoviliario.getText())+
                  Float.parseFloat(txtotrodgastosadmon.getText()));
            String suma= String.valueOf(sum);
            txttotsladmon.setText(suma);
            float sum_egresos;
            sum_egresos=(Float.parseFloat(txttotaloperacion.getText())+Float.parseFloat(txttotsladmon.getText()));
            String suma_egresos= String.valueOf(sum_egresos);
            txttotalegresos.setText(suma_egresos);
            float utilidad;
            utilidad=(Float.parseFloat(txtingnetos.getText())-Float.parseFloat(txttotalegresos.getText()));
            String utilida_neta= String.valueOf(utilidad);
            txtutilidad.setText(utilida_neta);
        }else
           txtdepreequimedico.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtdepreequimedicoKeyReleased

    private void txtdepremoviliarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepremoviliarioKeyReleased
        String numero=txtdepremoviliario.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpapeleria.getText()) + Float.parseFloat(txtdeprevehiculos.getText())+
                  Float.parseFloat(txtdepreequimedico.getText())+Float.parseFloat(txtdepremoviliario.getText())+
                  Float.parseFloat(txtotrodgastosadmon.getText()));
            String suma= String.valueOf(sum);
            txttotsladmon.setText(suma);
            float sum_egresos;
            sum_egresos=(Float.parseFloat(txttotaloperacion.getText())+Float.parseFloat(txttotsladmon.getText()));
            String suma_egresos= String.valueOf(sum_egresos);
            txttotalegresos.setText(suma_egresos);
            float utilidad;
            utilidad=(Float.parseFloat(txtingnetos.getText())-Float.parseFloat(txttotalegresos.getText()));
            String utilida_neta= String.valueOf(utilidad);
            txtutilidad.setText(utilida_neta);
        }else
           txtdepremoviliario.requestFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtdepremoviliarioKeyReleased

    private void txtotrodgastosadmonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotrodgastosadmonKeyReleased
        String numero=txtotrodgastosadmon.getText();
        if(numero.equals("")==false){
            float sum;
            sum=(Float.parseFloat(txtpapeleria.getText()) + Float.parseFloat(txtdeprevehiculos.getText())+
                  Float.parseFloat(txtdepreequimedico.getText())+Float.parseFloat(txtdepremoviliario.getText())+
                  Float.parseFloat(txtotrodgastosadmon.getText()));
            String suma= String.valueOf(sum);
            txttotsladmon.setText(suma);
            float sum_egresos;
            sum_egresos=(Float.parseFloat(txttotaloperacion.getText())+Float.parseFloat(txttotsladmon.getText()));
            String suma_egresos= String.valueOf(sum_egresos);
            txttotalegresos.setText(suma_egresos);
            float utilidad;
            utilidad=(Float.parseFloat(txtingnetos.getText())-Float.parseFloat(txttotalegresos.getText()));
            String utilida_neta= String.valueOf(utilidad);
            txtutilidad.setText(utilida_neta);
        }else
           txtotrodgastosadmon.requestFocus();     // TODO add your handling code here:
    }//GEN-LAST:event_txtotrodgastosadmonKeyReleased

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed

    }//GEN-LAST:event_registrarActionPerformed

    private void registrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrarKeyTyped

    }//GEN-LAST:event_registrarKeyTyped

    private void txtdepreequimedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepreequimedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepreequimedicoActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        PrincipalAdministrador.escritorio.removeAll();
        if (estacerrado(menu)) {
            menu = new pnl_menu();
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            menu.setSize(width, Height);
            escritorio.add(menu);
            menu.show();
            new elegir.elegir_contabilidad(a, true).setVisible(true);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txttotalingresosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalingresosKeyReleased
        String numero=txttotalingresos.getText();
        if(numero.equals("")==false){
            float ingreso_neto;
            ingreso_neto=(Float.parseFloat(txttotalingresos.getText())-Float.parseFloat(txtdescuento.getText()));
            String suma_ingresoneto= String.valueOf(ingreso_neto);
            txtingnetos.setText(suma_ingresoneto);
        }else
           txttotalingresos.requestFocus();            // TODO add your handling code here:
    }//GEN-LAST:event_txttotalingresosKeyReleased

    private void txttotalingresosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalingresosKeyTyped
         char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txttotalingresosKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButtomRectangle btnimprimir;
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel numFac;
    private javax.swing.JPanel pnlegresos;
    private javax.swing.JPanel pnlegresos1;
    private javax.swing.JPanel pnlingresos;
    public static principal.MaterialButton registrar;
    private java.awt.TextField txtdepreequimedico;
    private java.awt.TextField txtdepremoviliario;
    private java.awt.TextField txtdeprevehiculos;
    private java.awt.TextField txtdescuento;
    private java.awt.TextField txtimpuestos;
    private java.awt.TextField txtingnetos;
    private java.awt.TextField txtotrodgastosadmon;
    private java.awt.TextField txtotrosgastos;
    private java.awt.TextField txtpapeleria;
    private java.awt.TextField txtpublicidad;
    private java.awt.TextField txtsueysa;
    private java.awt.TextField txttotalegresos;
    private java.awt.TextField txttotalingresos;
    private java.awt.TextField txttotaloperacion;
    private java.awt.TextField txttotsladmon;
    private java.awt.TextField txtutilidad;
    // End of variables declaration//GEN-END:variables
}
