/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ambulancia;
import registro_examen.*;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import cafeteria.OpcionesAl;
import paneles.*;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import net.proteanit.sql.DbUtils;
import static principal.PrincipalAdministrador.escritorio;
import lista_productos_servicios.Producto;
import java.awt.HeadlessException;
import lista_productos_servicios.ProductoDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import principal.GenerarCodigos;
/**
 *
 * @author Rojeru San
 */
public class ambulancia extends javax.swing.JInternalFrame {
SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
Connection con=null;
Date dato = null;
ResultSet rs=null;
PreparedStatement pst=null;
static Conexion cc = new Conexion();
 static Connection cn = cc.ConnectDB();
     ProductoDAO pdao = new ProductoDAO();
     DefaultTableModel modelo = new DefaultTableModel();
    String idp;
    int cant;
    double pre;
    double tpagar;
    /**
     * Creates new form NewJInternalFrame
     */
     public boolean estacerrado(Object obj) {
        JInternalFrame[] activos = escritorio.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }
 int filas;
    DefaultTableModel m;
    public ambulancia() {
        initComponents();
        tablaCaja.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tablaCaja.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        tableCaja.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tableCaja.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        //this.setFrameIcon(new ImageIcon(getClass().getResource("/imagenes/caja/icono.png")));
        tablaCaja.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con= Conexion.ConnectDB();
        Get_Data();
        thishide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        thishide = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlChange = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        c_search_tbl = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCaja = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numFac = new javax.swing.JLabel();
        txtorigen = new app.bolivia.swing.JCTextField();
        txtkm = new app.bolivia.swing.JCTextField();
        txtdestino = new app.bolivia.swing.JCTextField();
        jPanel4 = new javax.swing.JPanel();
        txtpaciente = new app.bolivia.swing.JCTextField();
        txtFecha = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVender1 = new principal.MaterialButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        btns_paciente = new principal.MaterialButton();
        btnservicios = new principal.MaterialButton();
        txtmedicoadmin = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        btns_admin = new principal.MaterialButton();
        btns_medico1 = new principal.MaterialButton();
        txtconductor = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        txtambulancia = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btns_medico2 = new principal.MaterialButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCaja = new javax.swing.JTable();
        txttotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCancelar = new principal.MaterialButton();
        btnVender = new principal.MaterialButton();
        quitar = new principal.MaterialButton();
        btnedit = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 111, 177));
        jPanel2.setForeground(new java.awt.Color(12, 140, 143));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/test_48.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(thishide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 747, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(thishide, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.setLayout(new java.awt.CardLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(769, 582));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ambulance_64.png"))); // NOI18N
        jLabel7.setText("Ambulancia");

        pnlChange.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        c_search_tbl.setBackground(new java.awt.Color(204, 204, 204));
        c_search_tbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c_search_tbl.setForeground(new java.awt.Color(0, 0, 0));
        c_search_tbl.setToolTipText("");
        c_search_tbl.setCaretColor(new java.awt.Color(0, 0, 0));
        c_search_tbl.setFocusCycleRoot(true);
        c_search_tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c_search_tbl.setInheritsPopupMenu(true);
        c_search_tbl.setPlaceholder("Buscar Nombre");
        c_search_tbl.setPreferredSize(new java.awt.Dimension(400, 32));
        c_search_tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_search_tblActionPerformed(evt);
            }
        });
        c_search_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_search_tblKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(c_search_tbl, gridBagConstraints);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableCaja.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Domicilio", "Telefono"
            }
        ));
        tableCaja.setGridColor(new java.awt.Color(255, 255, 255));
        tableCaja.setRowHeight(20);
        tableCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCajaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCaja);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout pnlChangeLayout = new javax.swing.GroupLayout(pnlChange);
        pnlChange.setLayout(pnlChangeLayout);
        pnlChangeLayout.setHorizontalGroup(
            pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChangeLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1)
                    .addGap(5, 5, 5)))
        );
        pnlChangeLayout.setVerticalGroup(
            pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
            .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeLayout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, "card2");

        jTabbedPane2.addTab("Registros", jPanel10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(769, 582));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 128, 131));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ambulance_64.png"))); // NOI18N
        jLabel14.setText("Ambulancia");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 111, 177));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CODIGO DE EXAMEN");

        numFac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numFac.setForeground(new java.awt.Color(0, 111, 177));
        numFac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numFac.setText("NO. VENTA");

        txtorigen.setBackground(new java.awt.Color(255, 255, 255));
        txtorigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtorigen.setForeground(new java.awt.Color(0, 0, 0));
        txtorigen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtorigen.setPlaceholder("LUGAR ORIGEN");

        txtkm.setBackground(new java.awt.Color(255, 255, 255));
        txtkm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtkm.setForeground(new java.awt.Color(0, 0, 0));
        txtkm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtkm.setPlaceholder("KM RECORRIDOS");

        txtdestino.setBackground(new java.awt.Color(255, 255, 255));
        txtdestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdestino.setForeground(new java.awt.Color(0, 0, 0));
        txtdestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdestino.setPlaceholder("LUGAR DESTINO");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numFac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numFac)
                .addGap(18, 18, 18)
                .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpaciente.setEditable(false);
        txtpaciente.setBorder(null);
        txtpaciente.setForeground(new java.awt.Color(58, 159, 171));
        txtpaciente.setToolTipText("");
        txtpaciente.setEnabled(false);
        txtpaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpaciente.setPlaceholder("PACIENTE ATENDIDO");
        jPanel4.add(txtpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 250, 30));

        txtFecha.setBorder(null);
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFecha.setPlaceholder("FECHA");
        jPanel4.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-cliente.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-calendario.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnVender1.setBackground(new java.awt.Color(0, 111, 177));
        btnVender1.setForeground(new java.awt.Color(255, 255, 255));
        btnVender1.setText("BUSCAR INSUMOS");
        btnVender1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVender1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVender1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnVender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 190, 48));

        jSeparator1.setBackground(new java.awt.Color(58, 159, 171));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 12, 10, 200));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/HODUMEDIC_1.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 160));

        btns_paciente.setBackground(new java.awt.Color(0, 111, 177));
        btns_paciente.setBorder(null);
        btns_paciente.setForeground(new java.awt.Color(255, 255, 255));
        btns_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_caja.png"))); // NOI18N
        btns_paciente.setText("buscar");
        btns_paciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btns_paciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btns_paciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btns_paciente.setRippleColor(new java.awt.Color(60, 63, 65));
        btns_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_pacienteActionPerformed(evt);
            }
        });
        jPanel4.add(btns_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 80, 50));

        btnservicios.setBackground(new java.awt.Color(0, 111, 177));
        btnservicios.setForeground(new java.awt.Color(255, 255, 255));
        btnservicios.setText("BUSCAR SERVICIOS");
        btnservicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnservicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserviciosActionPerformed(evt);
            }
        });
        jPanel4.add(btnservicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 190, 48));

        txtmedicoadmin.setEditable(false);
        txtmedicoadmin.setBackground(new java.awt.Color(204, 204, 204));
        txtmedicoadmin.setBorder(null);
        txtmedicoadmin.setForeground(new java.awt.Color(58, 159, 171));
        txtmedicoadmin.setToolTipText("");
        txtmedicoadmin.setEnabled(false);
        txtmedicoadmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmedicoadmin.setPlaceholder("MEDICO/ENFERMERA(OPCIONAL)");
        jPanel4.add(txtmedicoadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 250, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/atiende.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 310, -1));

        btns_admin.setBackground(new java.awt.Color(0, 111, 177));
        btns_admin.setBorder(null);
        btns_admin.setForeground(new java.awt.Color(255, 255, 255));
        btns_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_caja.png"))); // NOI18N
        btns_admin.setText("buscar");
        btns_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btns_admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btns_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btns_admin.setRippleColor(new java.awt.Color(60, 63, 65));
        btns_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_adminActionPerformed(evt);
            }
        });
        jPanel4.add(btns_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 80, 50));

        btns_medico1.setBackground(new java.awt.Color(0, 111, 177));
        btns_medico1.setBorder(null);
        btns_medico1.setForeground(new java.awt.Color(255, 255, 255));
        btns_medico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_caja.png"))); // NOI18N
        btns_medico1.setText("buscar");
        btns_medico1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btns_medico1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btns_medico1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btns_medico1.setRippleColor(new java.awt.Color(60, 63, 65));
        btns_medico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_medico1ActionPerformed(evt);
            }
        });
        jPanel4.add(btns_medico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 80, 50));

        txtconductor.setEditable(false);
        txtconductor.setBorder(null);
        txtconductor.setForeground(new java.awt.Color(58, 159, 171));
        txtconductor.setToolTipText("");
        txtconductor.setEnabled(false);
        txtconductor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtconductor.setPlaceholder("CONDUCTOR");
        jPanel4.add(txtconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 250, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/indication.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 310, -1));

        txtambulancia.setBorder(null);
        txtambulancia.setForeground(new java.awt.Color(0, 0, 0));
        txtambulancia.setEnabled(false);
        txtambulancia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtambulancia.setPlaceholder("AMBULANCIA");
        jPanel4.add(txtambulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 250, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/num_room.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 310, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/indication.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 310, -1));

        btns_medico2.setBackground(new java.awt.Color(0, 111, 177));
        btns_medico2.setBorder(null);
        btns_medico2.setForeground(new java.awt.Color(255, 255, 255));
        btns_medico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_caja.png"))); // NOI18N
        btns_medico2.setText("buscar");
        btns_medico2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btns_medico2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btns_medico2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btns_medico2.setRippleColor(new java.awt.Color(60, 63, 65));
        btns_medico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_medico2ActionPerformed(evt);
            }
        });
        jPanel4.add(btns_medico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 80, 50));

        jPanel7.setBackground(new java.awt.Color(0, 111, 177));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));

        tablaCaja.setBackground(new java.awt.Color(0, 0, 0));
        tablaCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaCaja.setForeground(new java.awt.Color(255, 255, 255));
        tablaCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUCTO / SERVICIO", "PRECIO (L)", "CANTIDAD", "IMPORTE (L)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCaja.setDoubleBuffered(true);
        tablaCaja.setRowHeight(20);
        tablaCaja.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaCaja.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaCaja);

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        txttotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttotal.setText("SUBTOTAL: L");
        txttotal.setToolTipText("");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0.0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel6.setBorder(dropShadowBorder2);

        btnCancelar.setBackground(new java.awt.Color(0, 111, 177));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("LIMPIAR");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVender.setBackground(new java.awt.Color(0, 111, 177));
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("REGISTRAR EXAMEN");
        btnVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        quitar.setBackground(new java.awt.Color(0, 111, 177));
        quitar.setForeground(new java.awt.Color(255, 255, 255));
        quitar.setText("QUITAR");
        quitar.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Quitar</h4> </body> </html>");
        quitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(0, 111, 177));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Actualizar");
        btnedit.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Quitar</h4> </body> </html>");
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 948, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nuevo Registro", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Registro de Ventas");

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //genera el codigo registro de examen 
    private void numeros() {
        int j;
        int cont = 1;
        String num = "";
        String c = "";
        String SQL = "SELECT MAX(codigo) FROM test_ambulancia";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                numFac.setText("RA0001");
            } else {
                char r1 = c.charAt(2);
                char r2 = c.charAt(3);
                char r3 = c.charAt(4);
                char r4 = c.charAt(5);
                String r = "";
                r = "" + r1 + r2 + r3 + r4;
                j = Integer.parseInt(r);
                GenerarCodigos gen = new GenerarCodigos();
                gen.generar(j);
                numFac.setText("RA" + gen.serie());

            }

        } catch (SQLException ex) {
            Logger.getLogger(OpcionesAl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
        return formatofecha.format(fecha);

    }

    void limpiaCampos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaCaja.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        txtpaciente.setText("");
        txtorigen.setText("");
        txtmedicoadmin.setText("");
        txtconductor.setText("");
        txtambulancia.setText("");
        lblTotal.setText("0.0");
        txtFecha.setText(fechaactual());
        btnedit.setVisible(false);
        thishide.setVisible(false);
        numeros();
    }
  private void Get_Data(){
        limpiaCampos();
        String sql="select codigo as 'Codigo',paciente as 'Paciente', medico_1 as 'Medico(a)/Enfermera(o)',"
                + " conductor as 'Conductor',ambulancia as 'Ambulancia',origen as'Origen',destino as 'Destino',"
                + "km as 'Kilometros',fecha as 'Fecha y Hora', total as 'Total (L)' from test_ambulancia";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tableCaja.setModel(DbUtils.resultSetToTableModel(rs));
         tableCaja.removeColumn(tableCaja.getColumnModel().getColumn(0));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          } 
  }


    void actualizarStock() {
        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            Producto pr = new Producto();
            idp = tablaCaja.getValueAt(i, 0).toString();
            cant = Integer.parseInt(tablaCaja.getValueAt(i, 3).toString());
            pr = pdao.listarID_ambulancia(idp);
            int sa = pr.getStock() - cant;
            pdao.actualizarStock_ambulancia(sa, idp);

        }
    }
//    paciente,num_fac,estado,fecha,isv,codigo,nombre_p, precio, cantidad,importe, subtotal, total
    void print_bill(){
//        laboratorio em;// Instaciamos la clase empleado
//        List <laboratorio>lista = new ArrayList<>(); //Creamos una lista de empleados con ArrayList para obtener cada empleado
//        for(int i=0; i<tablaCaja.getRowCount(); i++){ // Iterena cada fila de la tabla
//            em = new laboratorio(txtpaciente.getText(),numFac.getText(),condiciones(Estado_actual), txtFecha.getText(),isv.getText(),tablaCaja.getValueAt(i, 0).toString(),tablaCaja.getValueAt(i,1).toString(), //Tomamos de la tabla el valor de cada columna y creamos un objeto empleado
//            tablaCaja.getValueAt(i, 2).toString(),tablaCaja.getValueAt(i, 3).toString(),tablaCaja.getValueAt(i, 4).toString(),lblsubtotal.getText(),lblTotal.getText());
//            lista.add(em); //Agregamos el objeto empleado a la lista
//        }
//        JasperReport reporte; // Instaciamos el objeto reporte
//        String path = "src\\reportes\\caja_laboratorio.jasper"; //Ponemos la localizacion del reporte creado
//        try {
//            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Se carga el reporte de su localizacion
//            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(lista)); //Agregamos los parametros para llenar el reporte
//            JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reportes
//            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Se declara con dispose_on_close para que no se cierre el programa cuando se cierre el reporte
//            viewer.setVisible(true); //Se vizualiza el reporte
//        } catch (JRException ex) {
//           
//        } 
}

     private void ingresar_detalle(){
    for (int i = 0; i <tablaCaja.getRowCount(); i++) {
        String codigo= tablaCaja.getModel().getValueAt(i, 0).toString();
        String p_s= tablaCaja.getModel().getValueAt(i, 1).toString();
        String precio= tablaCaja.getModel().getValueAt(i, 2).toString();
        String cantidad= tablaCaja.getModel().getValueAt(i, 3).toString();
        String importe= tablaCaja.getModel().getValueAt(i, 4).toString();
        String sql= "insert into detalle_test_ambulancia(idventa,codigo,p_s,precio,cantidad,importe) values ('"+numFac.getText()+"','" +codigo+"','" + p_s +"','" +precio+"','" +cantidad+"','" +importe+ "')";

        try{
            con=Conexion.ConnectDB();
            pst=con.prepareStatement(sql);
            pst.execute();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }
         }
    private void show_detalle(){
        String sql="select codigo as 'Codigo',p_s as 'Producto/Servicio',precio as 'Precio',cantidad as 'Cantidad',importe as 'Importe' from detalle_test_ambulancia where idventa='" + numFac.getText() + "' ";
        try{
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         tablaCaja.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}    
    }

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void c_search_tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_search_tblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_search_tblActionPerformed

    private void c_search_tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_search_tblKeyReleased
        // search btn code
        String name = c_search_tbl.getText();
        try {

            DefaultTableModel dt = (DefaultTableModel) tableCaja.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM test_ambulancia WHERE paciente LIKE '%"+name+"%' ");

                    while (rs.next()) {
                        Vector v = new Vector();
                        v.add(rs.getString(1));
                        v.add(rs.getString(2));
                        v.add(rs.getString(3));
                        v.add(rs.getString(4));
                        v.add(rs.getString(5));
                        v.add(rs.getString(6));
                        v.add(rs.getString(7));
                        v.add(rs.getString(8));
                        v.add(rs.getString(9));

                        dt.addRow(v);
                    }

        } catch (Exception e) {
            Get_Data();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_c_search_tblKeyReleased
    //select idventa as 'Codigo',isv as 'ISV', paciente as 'Paciente', fecha as 'Fecha',estado_pago as 'Estado de Pago',total as 'Total (L)'
    private void tableCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCajaMouseClicked
        try {
            int row= tableCaja.getSelectedRow();
            numFac.setText(tableCaja.getModel().getValueAt(row,0).toString());
            txtpaciente.setText(tableCaja.getModel().getValueAt(row,1).toString());
            txtmedicoadmin.setText(tableCaja.getModel().getValueAt(row,2).toString());
            lblTotal.setText(tableCaja.getModel().getValueAt(row,7).toString());
            txtconductor.setText(tableCaja.getModel().getValueAt(row,3).toString()) ;
            txtambulancia.setText(tableCaja.getModel().getValueAt(row,4).toString()) ;
            txtorigen.setText(tableCaja.getModel().getValueAt(row,5).toString()) ;
            txtFecha.setText(tableCaja.getModel().getValueAt(row,6).toString()) ;
            txttotal.setText("TOTAL PAGADO: L");
            thishide.setVisible(true);
            btnVender.setEnabled(false);
            quitar.setEnabled(false);
            this.jTabbedPane2.setSelectedIndex(1);
            show_detalle();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableCajaMouseClicked

    private void btnVender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVender1ActionPerformed
        new lista_productos_servicios.productos_ambulancia(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnVender1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (thishide.isVisible()){
            limpiaCampos();
            jTabbedPane2.setSelectedIndex(0); 
            btnVender.setEnabled(true);
            quitar.setEnabled(true);
        }else{
        limpiaCampos();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if (this.tablaCaja.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("IMPOSIBLE INGRESAR");
            er.msj1.setText("EXAMEN");
            er.setVisible(true);
        } else {
        try{
            con=Conexion.ConnectDB();
            if (txtpaciente.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Paciente","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
//            if (txtmedicoadmin.getText().equals("")) {
//                JOptionPane.showMessageDialog( this, "Ingrese la Persona que Realiza el Examen","Error", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
            if (txtconductor.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Conductor de la Ambulancia","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }  
            if (txtambulancia.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Ambulancia","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtorigen.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese el Origen del Cual Partio Ambulancia","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtdestino.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese el Destino al cual Fue la ambulancia","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtkm.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese los Kilometros de la Ambulancia","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtFecha.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Fecha","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
               // insertar datos en test_laboratorio
            String sql= "insert into test_ambulancia(codigo,paciente,medico_1,conductor,ambulancia,origen,destino,km,fecha,total) values ('"+numFac.getText()+"','" +txtpaciente.getText()+"','" +txtmedicoadmin.getText()+"','" +txtconductor.getText()+"','"+txtambulancia.getText()+"','" +txtorigen.getText()+"','"+txtdestino.getText()+"','"+txtkm.getText()+"','" + txtFecha.getText()+"','" +lblTotal.getText() + "')";
            pst=con.prepareStatement(sql);
            pst.execute();
            actualizarStock(); 
            ingresar_detalle();
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            sa.titulo.setText("¡HECHO!");
            sa.msj.setText("REGISTRADO");
            sa.msj1.setText("CON ÉXITO");
            sa.setVisible(true);
            print_bill();
            this.jTabbedPane2.setSelectedIndex(0);
            Get_Data();
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        } 
        }
    }//GEN-LAST:event_btnVenderActionPerformed
    public static void calcular() {
        String pre;
        String can;
        double total = 0;
        double precio;
        int cantidad;
        double imp = 0.0;

        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            pre = tablaCaja.getValueAt(i, 2).toString();
            can = tablaCaja.getValueAt(i, 3).toString();
            precio = Double.parseDouble(pre);
            cantidad = Integer.parseInt(can);
            imp = precio * cantidad;
            total = total + imp;
            tablaCaja.setValueAt(Math.rint(imp * 100) / 100, i, 4);

        }
        lblTotal.setText("" + Math.rint(total * 100) / 100);
    }
    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCaja.getModel();
        if (modelo.getRowCount() > 0) {

            int fila = this.tablaCaja.getSelectedRow();
            if (this.tablaCaja.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                modelo.removeRow(fila);
                calcular();
            }
        }
    }//GEN-LAST:event_quitarActionPerformed

    private void btnserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserviciosActionPerformed
        new lista_servicios.lista_ambulancia(new JFrame(), true).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnserviciosActionPerformed

    private void btns_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_pacienteActionPerformed
        int P = JOptionPane.showConfirmDialog(null,"El Paciente ya se Ingreso?","Confirmación",JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION){ 
                pacientes.lista_pacientes_laboratorio.cual="5";
                new pacientes.lista_pacientes_laboratorio(new JFrame(), true).setVisible(true);
            }else if (P == JOptionPane.NO_OPTION){
//                pacientes.modalpaciente mp =
                new pacientes.modal_paciente(new JFrame(), true).setVisible(true);
//                mp.titulo.setText("REGISTRAR PACIENTE");
//                mp.registrar.setText("REGISTRAR");
//                mp.setVisible(true);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btns_pacienteActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
//        try{
//            con=Conexion.ConnectDB();
//            String sql= "update test_laboratorio set estado_pago='" + condiciones(Estado_actual) + "' where idventa='" + numFac.getText()+ "'";
//            pst=con.prepareStatement(sql);
//            pst.execute();
//            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
//            sa.titulo.setText("¡HECHO!");
//            sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
//            sa.msj1.setText("");
//            sa.setVisible(true);
//            print_bill();
//
//        }catch(HeadlessException | SQLException ex){
//            JOptionPane.showMessageDialog(this,ex);
//        }          // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btns_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_adminActionPerformed
        empleados.lista_empleados_admin.cual="5";
        new empleados.lista_empleados_admin(new JFrame(), true).setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btns_adminActionPerformed

    private void btns_medico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_medico1ActionPerformed
        new lista_ambulancias(new JFrame(), true).setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btns_medico1ActionPerformed

    private void btns_medico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_medico2ActionPerformed
        empleados.lista_empleados_mindica.cual="5";
        new empleados.lista_empleados_mindica(new JFrame(), true).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btns_medico2ActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnCancelar;
    private principal.MaterialButton btnVender;
    private principal.MaterialButton btnVender1;
    private principal.MaterialButton btnedit;
    private principal.MaterialButton btns_admin;
    private principal.MaterialButton btns_medico1;
    private principal.MaterialButton btns_medico2;
    private principal.MaterialButton btns_paciente;
    private principal.MaterialButton btnservicios;
    private app.bolivia.swing.JCTextField c_search_tbl;
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JLabel lblTotal;
    public static javax.swing.JLabel numFac;
    private javax.swing.JPanel pnlChange;
    private principal.MaterialButton quitar;
    public static javax.swing.JTable tablaCaja;
    private javax.swing.JTable tableCaja;
    private javax.swing.JLabel thishide;
    private app.bolivia.swing.JCTextField txtFecha;
    public static app.bolivia.swing.JCTextField txtambulancia;
    public static app.bolivia.swing.JCTextField txtconductor;
    private app.bolivia.swing.JCTextField txtdestino;
    private app.bolivia.swing.JCTextField txtkm;
    public static app.bolivia.swing.JCTextField txtmedicoadmin;
    private app.bolivia.swing.JCTextField txtorigen;
    public static app.bolivia.swing.JCTextField txtpaciente;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
