/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia;
import ServiciosYConexion.Conexion;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import cafeteria.OpcionesAl;
import java.util.Date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import net.proteanit.sql.DbUtils;
import static principal.PrincipalAdministrador.escritorio;
import lista_productos_servicios.Producto;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import lista_productos_servicios.ProductoDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import generadores_codigo.*;

/**
 *
 * @author Rojeru San
 */
public class caja_cobro extends javax.swing.JInternalFrame {
SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
Connection con=null;
Date dato = null;
ResultSet rs=null;
PreparedStatement pst=null;
static Conexion cc = new Conexion();
 static Connection cn = cc.ConnectDB();
     ProductoDAO pdao = new ProductoDAO();
     DefaultTableModel modelo = new DefaultTableModel();
    String idp;
    int cant;
    double pre;
    double tpagar;
    /**
     * Creates new form NewJInternalFrame
     */
     public boolean estacerrado(Object obj) {
        JInternalFrame[] activos = escritorio.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }
 int filas;
    DefaultTableModel m;
    public caja_cobro() {
        initComponents();
        tablaCaja.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tablaCaja.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        tableCaja.getTableHeader().setDefaultRenderer(new principal.EstiloTablaHeader());
        tableCaja.setDefaultRenderer(Object.class, new principal.EstiloTablaRenderer());
        //this.setFrameIcon(new ImageIcon(getClass().getResource("/imagenes/caja/icono.png")));
        tablaCaja.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con= Conexion.ConnectDB();
        Get_Data();
        thishide.setVisible(false);
        btnmedico.setVisible(false);
        txtmedicoindica.setVisible(false);
        lblmedico.setVisible(false);
        numeros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        selectmedico = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        thishide = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlChange = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        c_search_tbl = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCaja = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numFac = new javax.swing.JLabel();
        txtFecha = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtpaciente = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        btnProducto = new principal.MaterialButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        btnmedico = new principal.MaterialButton();
        txtmedicoindica = new app.bolivia.swing.JCTextField();
        lblmedico = new javax.swing.JLabel();
        rbninterno = new javax.swing.JRadioButton();
        rbnexterno = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCaja = new javax.swing.JTable();
        txttotal1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCancelar = new principal.MaterialButton();
        btnguardar = new principal.MaterialButton();
        quitar = new principal.MaterialButton();
        btnprint = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 111, 177));
        jPanel2.setForeground(new java.awt.Color(12, 140, 143));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/test_48.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registros Farmacia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(thishide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(thishide, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.setLayout(new java.awt.CardLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(769, 582));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Caja_64.png"))); // NOI18N
        jLabel7.setText("Caja");

        pnlChange.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        c_search_tbl.setBackground(new java.awt.Color(204, 204, 204));
        c_search_tbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c_search_tbl.setForeground(new java.awt.Color(0, 0, 0));
        c_search_tbl.setToolTipText("");
        c_search_tbl.setCaretColor(new java.awt.Color(0, 0, 0));
        c_search_tbl.setFocusCycleRoot(true);
        c_search_tbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        c_search_tbl.setInheritsPopupMenu(true);
        c_search_tbl.setPlaceholder("Buscar Nombre");
        c_search_tbl.setPreferredSize(new java.awt.Dimension(400, 32));
        c_search_tbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_search_tblActionPerformed(evt);
            }
        });
        c_search_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_search_tblKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(c_search_tbl, gridBagConstraints);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tableCaja = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        tableCaja.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Domicilio", "Telefono"
            }
        ));
        tableCaja.setGridColor(new java.awt.Color(255, 255, 255));
        tableCaja.setRowHeight(20);
        tableCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCajaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCaja);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout pnlChangeLayout = new javax.swing.GroupLayout(pnlChange);
        pnlChange.setLayout(pnlChangeLayout);
        pnlChangeLayout.setHorizontalGroup(
            pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1286, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChangeLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1)
                    .addGap(5, 5, 5)))
        );
        pnlChangeLayout.setVerticalGroup(
            pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChangeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
            .addGroup(pnlChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChangeLayout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, "card2");

        jTabbedPane2.addTab("Registro de Ventas", jPanel10);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(769, 582));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 128, 131));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Caja_64.png"))); // NOI18N
        jLabel14.setText("Caja");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 111, 177));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CODIGO DE FACTURA");
        jPanel22.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 306, -1));

        numFac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numFac.setForeground(new java.awt.Color(0, 111, 177));
        numFac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numFac.setText("NO. VENTA");
        jPanel22.add(numFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 32, 306, -1));

        txtFecha.setBorder(null);
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);
        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFecha.setPlaceholder("FECHA");
        jPanel22.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-calendario.png"))); // NOI18N
        jPanel22.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtpaciente.setBorder(null);
        txtpaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtpaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpaciente.setPlaceholder("NOMBRE DEL CLIENTE");
        jPanel4.add(txtpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/campo-cliente.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 310, -1));

        btnProducto.setBackground(new java.awt.Color(0, 111, 177));
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setText("BUSCAR PRODUCTOS");
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        jPanel4.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 190, 48));

        jSeparator1.setBackground(new java.awt.Color(58, 159, 171));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 12, 10, 200));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/HODUMEDIC_1.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 160));

        btnmedico.setBackground(new java.awt.Color(0, 111, 177));
        btnmedico.setBorder(null);
        btnmedico.setForeground(new java.awt.Color(255, 255, 255));
        btnmedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_caja.png"))); // NOI18N
        btnmedico.setText("buscar");
        btnmedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmedico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmedico.setRippleColor(new java.awt.Color(60, 63, 65));
        btnmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicoActionPerformed(evt);
            }
        });
        jPanel4.add(btnmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 80, 50));

        txtmedicoindica.setBackground(new java.awt.Color(255, 255, 255));
        txtmedicoindica.setBorder(null);
        txtmedicoindica.setForeground(new java.awt.Color(0, 0, 0));
        txtmedicoindica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmedicoindica.setPlaceholder("MEDICO QUE INDICA");
        jPanel4.add(txtmedicoindica, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 240, 30));

        lblmedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/indication.png"))); // NOI18N
        jPanel4.add(lblmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 310, -1));

        rbninterno.setBackground(new java.awt.Color(255, 255, 255));
        selectmedico.add(rbninterno);
        rbninterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbninterno.setForeground(new java.awt.Color(0, 0, 0));
        rbninterno.setText("MEDICO INTERNO");
        rbninterno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbninterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbninternoActionPerformed(evt);
            }
        });
        jPanel4.add(rbninterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        rbnexterno.setBackground(new java.awt.Color(255, 255, 255));
        selectmedico.add(rbnexterno);
        rbnexterno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbnexterno.setForeground(new java.awt.Color(0, 0, 0));
        rbnexterno.setText("MEDICO EXTERNO");
        rbnexterno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbnexterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbnexternoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rbnexternoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbnexternoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbnexternoMouseReleased(evt);
            }
        });
        rbnexterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnexternoActionPerformed(evt);
            }
        });
        rbnexterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbnexternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbnexternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rbnexternoKeyTyped(evt);
            }
        });
        jPanel4.add(rbnexterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 111, 177));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 111, 177), 3));

        tablaCaja.setBackground(new java.awt.Color(0, 0, 0));
        tablaCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaCaja.setForeground(new java.awt.Color(255, 255, 255));
        tablaCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUCTO / SERVICIO", "PRECIO (L)", "CANTIDAD", "IMPORTE (L)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCaja.setDoubleBuffered(true);
        tablaCaja.setRowHeight(20);
        tablaCaja.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaCaja.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaCaja);

        txttotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttotal1.setForeground(new java.awt.Color(255, 255, 255));
        txttotal1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttotal1.setText("TOTAL: L");
        txttotal1.setToolTipText("");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0.0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txttotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel6.setBorder(dropShadowBorder2);

        btnCancelar.setBackground(new java.awt.Color(0, 111, 177));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("LIMPIAR");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(0, 111, 177));
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("        GUARDAR          ");
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        quitar.setBackground(new java.awt.Color(0, 111, 177));
        quitar.setForeground(new java.awt.Color(255, 255, 255));
        quitar.setText("QUITAR");
        quitar.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Quitar</h4> </body> </html>");
        quitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        btnprint.setBackground(new java.awt.Color(0, 111, 177));
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setText("IMPRIMIR");
        btnprint.setToolTipText("<html> <head> <style> #contenedor{background:#3A9FAB;color:white; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Quitar</h4> </body> </html>");
        btnprint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nueva Factura", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Registro de Ventas");

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void numeros() {
        GenerarCodigosCajaFarmacia gen = new GenerarCodigosCajaFarmacia();
        gen.generar();
    }

   public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatofecha.format(fecha);

    }
   //desabilitar botones y cajas de texto cauado se miren detalles de venta
   void botones(){
    txtpaciente.setEnabled(false);
    btnProducto.setEnabled(false);
    quitar.setEnabled(false);
    rbnexterno.setEnabled(false);
    rbninterno.setEnabled(false);
}
   
    void limpiaCampos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaCaja.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        txtpaciente.setText("");
        txtmedicoindica.setText("");
        lblTotal.setText("0.0");
        txtFecha.setText(fechaactual());
        thishide.setVisible(false);
        btnmedico.setVisible(false);
        txtmedicoindica.setVisible(false);
        lblmedico.setVisible(false);
        selectmedico.clearSelection();
        txtpaciente.setEnabled(true);
        btnProducto.setEnabled(true);
        quitar.setEnabled(true);
        rbnexterno.setEnabled(true);
        rbninterno.setEnabled(true);
        btnguardar.setEnabled(true);
        btnprint.setEnabled(false);
        btnProducto.setEnabled(true);
        numeros();
    }
  private void Get_Data(){
       txtFecha.setText(fechaactual());
        String sql="select idventa as 'codigo'," +
"                medico as 'Medico que Indica'," +
"               cliente as 'Cliente'," +
"              fecha as 'Fecha'," +
"              total as 'Total'" +
"              from caja_farmacia ";

        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tableCaja.setModel(DbUtils.resultSetToTableModel(rs));
         tableCaja.removeColumn(tableCaja.getColumnModel().getColumn(0));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          } 
  }


    void actualizarStock() {
        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            Producto pr = new Producto();
            idp = tablaCaja.getValueAt(i, 0).toString();
            cant = Integer.parseInt(tablaCaja.getValueAt(i, 3).toString());
            pr = pdao.listarID_inventarioFarmacia(idp);
            int sa = pr.getStock() - cant;
            pdao.actualizarStock_farmacia(sa, idp);

        }
    }
//    paciente,num_fac,estado,fecha,isv,codigo,nombre_p, precio, cantidad,importe, subtotal, total
    void print_bill(){
        class_factura_farmacia em;// Instaciamos la clase empleado
        List <class_factura_farmacia>lista = new ArrayList<>(); //Creamos una lista de empleados con ArrayList para obtener cada empleado
        for(int i=0; i<tablaCaja.getRowCount(); i++){ // Iterena cada fila de la tabla
            em = new class_factura_farmacia(txtpaciente.getText(),numFac.getText(), txtFecha.getText(),tablaCaja.getValueAt(i, 0).toString(),tablaCaja.getValueAt(i,1).toString(), //Tomamos de la tabla el valor de cada columna y creamos un objeto empleado
            tablaCaja.getValueAt(i, 2).toString(),tablaCaja.getValueAt(i, 3).toString(),tablaCaja.getValueAt(i, 4).toString(),lblTotal.getText());
            lista.add(em); //Agregamos el objeto empleado a la lista
        }
        JasperReport reporte; // Instaciamos el objeto reporte
        String path = "src\\reportes\\caja_farmacia.jasper"; //Ponemos la localizacion del reporte creado
        try {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Se carga el reporte de su localizacion
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, new JRBeanCollectionDataSource(lista)); //Agregamos los parametros para llenar el reporte
            JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reportes
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Se declara con dispose_on_close para que no se cierre el programa cuando se cierre el reporte
            viewer.setVisible(true); //Se vizualiza el reporte
        } catch (JRException ex) {
           
        } 
}

     private void ingresar_detalle(){
    for (int i = 0; i <tablaCaja.getRowCount(); i++) {
        String codigo= tablaCaja.getModel().getValueAt(i, 0).toString();
        String producto= tablaCaja.getModel().getValueAt(i, 1).toString();
        String precio= tablaCaja.getModel().getValueAt(i, 2).toString();
        String cantidad= tablaCaja.getModel().getValueAt(i, 3).toString();
        String importe= tablaCaja.getModel().getValueAt(i, 4).toString();
        String sql= "insert into caja_detalle_farmacia(venta,"
                + "producto,"
                + "precio,"
                + "cantidad,"
                + "importe) values ('"+numFac.getText()+"','" 
                + producto +"','" 
                +precio+"','" 
                +cantidad+"','" 
                +importe+ "')";

        try{
            con=Conexion.ConnectDB();
            pst=con.prepareStatement(sql);
            pst.execute();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }
         }
private void show_detalle(){
            String sql="select id_detalle as 'Codigo',"
                    + "producto as 'Producto',"
                    + "precio as 'Precio',"
                    + "cantidad as 'Cantidad',"
                    + "importe as 'Importe' "
                    + "from caja_detalle_farmacia "
                    + "where venta='" + numFac.getText() + "'";
        try{
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         tablaCaja.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);    
            } 
}
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void c_search_tblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_search_tblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_search_tblActionPerformed

    private void c_search_tblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_search_tblKeyReleased
        // search btn code
        String name = c_search_tbl.getText();
        try {

            DefaultTableModel dt = (DefaultTableModel) tableCaja.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();
                ResultSet rs = s.executeQuery("select idventa as 'codigo'," +
"                medico as 'Medico que Indica'," +
"               cliente as 'Cliente'," +
"              fecha as 'Fecha'," +
"              total as 'Total'" +
"              from caja_farmacia WHERE cliente LIKE '%"+name+"%' ");

                    while (rs.next()) {
                        Vector v = new Vector();
                        v.add(rs.getString(1));
                        v.add(rs.getString(2));
                        v.add(rs.getString(3));
                        v.add(rs.getString(4));
                        v.add(rs.getString(5));

                        dt.addRow(v);
                    }

        } catch (Exception e) {
            Get_Data();

        }          // TODO add your handling code here:
    }//GEN-LAST:event_c_search_tblKeyReleased
    //select idventa as 'Codigo',isv as 'ISV', paciente as 'Paciente', fecha as 'Fecha',estado_pago as 'Estado de Pago',total as 'Total (L)'
    private void tableCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCajaMouseClicked
        try {
            int row= tableCaja.getSelectedRow();
            numFac.setText(tableCaja.getModel().getValueAt(row,0).toString());
            txtmedicoindica.setText(tableCaja.getModel().getValueAt(row,1).toString());
            txtpaciente.setText(tableCaja.getModel().getValueAt(row,2).toString());
            lblTotal.setText(tableCaja.getModel().getValueAt(row,4).toString());
            txtFecha.setText(tableCaja.getModel().getValueAt(row,3).toString()) ;
            this.btnguardar.setEnabled(false);
            this.jTabbedPane2.setSelectedIndex(1);
            botones();
            show_detalle();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }                // TODO add your handling code here:
    }//GEN-LAST:event_tableCajaMouseClicked

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        new productos_farmacia(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiaCampos();
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (this.tablaCaja.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("IMPOSIBLE INGRESAR");
            er.msj1.setText("EXAMEN");
            er.setVisible(true);
        } else {
        try{
            con=Conexion.ConnectDB();
            if (txtpaciente.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Nombre del Cliente","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtmedicoindica.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Medico que Indica el Examen","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }  
            if (txtFecha.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Ingrese Fecha","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
               // insertar datos en test_laboratorio
            String sql= "insert into caja_farmacia("
                    + "medico,"
                    + "cliente,"
                    + "fecha,"
                    + "total) values ('"
                    +txtmedicoindica.getText()+"','"
                    +txtpaciente.getText()+"','" 
                    + txtFecha.getText()+"','" 
                    +lblTotal.getText() + "')";
            pst=con.prepareStatement(sql);
            pst.execute();
            actualizarStock(); 
            ingresar_detalle();
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            sa.titulo.setText("¡HECHO!");
            sa.msj.setText("VENTA REGISTRADA");
            sa.msj1.setText("CON ÉXITO");
            sa.setVisible(true);
            btnprint.setEnabled(true);
            btnguardar.setEnabled(false);
            btnProducto.setEnabled(false);
            Get_Data();
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        } 
        }
    }//GEN-LAST:event_btnguardarActionPerformed
    public static void calcular() {
        String pre;
        String can;
        double total = 0;
        double precio;
        int cantidad;
        double imp = 0.0;

        for (int i = 0; i < tablaCaja.getRowCount(); i++) {
            pre = tablaCaja.getValueAt(i, 2).toString();
            can = tablaCaja.getValueAt(i, 3).toString();
            precio = Double.parseDouble(pre);
            cantidad = Integer.parseInt(can);
            imp = precio * cantidad;
            total = total + imp;
            tablaCaja.setValueAt(Math.rint(imp * 100) / 100, i, 4);

        }
        lblTotal.setText("" + Math.rint(total * 100) / 100);
    }
    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCaja.getModel();
        if (modelo.getRowCount() > 0) {

            int fila = this.tablaCaja.getSelectedRow();
            if (this.tablaCaja.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                modelo.removeRow(fila);
                calcular();
            }
        }
    }//GEN-LAST:event_quitarActionPerformed

    private void btnmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicoActionPerformed
        empleados.lista_empleados_mindica.cual="11";
        new empleados.lista_empleados_mindica(new JFrame(), true).setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btnmedicoActionPerformed

    private void rbninternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbninternoActionPerformed
        btnmedico.setVisible(true);
        txtmedicoindica.setVisible(true);
        lblmedico.setVisible(true);
        txtmedicoindica.setEnabled(false);
        txtmedicoindica.requestFocus();
        txtmedicoindica.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_rbninternoActionPerformed

    private void rbnexternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnexternoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoMouseClicked

    private void rbnexternoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnexternoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoMouseEntered

    private void rbnexternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnexternoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoMousePressed

    private void rbnexternoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnexternoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoMouseReleased

    private void rbnexternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnexternoActionPerformed
        btnmedico.setVisible(false);
        txtmedicoindica.setVisible(true);
        lblmedico.setVisible(true);
        txtmedicoindica.setEnabled(true);
        txtmedicoindica.requestFocus();
        txtmedicoindica.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoActionPerformed

    private void rbnexternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbnexternoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoKeyPressed

    private void rbnexternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbnexternoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoKeyReleased

    private void rbnexternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbnexternoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnexternoKeyTyped

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
       this.jTabbedPane2.setSelectedIndex(0);
        print_bill();
        limpiaCampos();// TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnCancelar;
    private principal.MaterialButton btnProducto;
    private principal.MaterialButton btnguardar;
    private principal.MaterialButton btnmedico;
    private principal.MaterialButton btnprint;
    private app.bolivia.swing.JCTextField c_search_tbl;
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblmedico;
    public static javax.swing.JLabel numFac;
    private javax.swing.JPanel pnlChange;
    private principal.MaterialButton quitar;
    private javax.swing.JRadioButton rbnexterno;
    private javax.swing.JRadioButton rbninterno;
    private javax.swing.ButtonGroup selectmedico;
    public static javax.swing.JTable tablaCaja;
    private javax.swing.JTable tableCaja;
    public static javax.swing.JLabel thishide;
    private app.bolivia.swing.JCTextField txtFecha;
    public static app.bolivia.swing.JCTextField txtmedicoindica;
    private app.bolivia.swing.JCTextField txtpaciente;
    private javax.swing.JLabel txttotal1;
    // End of variables declaration//GEN-END:variables
}
